# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Function used as part of other functions
#'
#'
#' @description relu-function
#' @param x input in the relu function
#'
#' @export
rcpprelu <- function(x) {
    .Call(`_SRCL_rcpprelu`, x)
}

#' Function used as part of other functions
#'
#'
#' @description negative relu-function
#' @param x input in the negative relu-function
#'
#' @export
rcpprelu_neg <- function(x) {
    .Call(`_SRCL_rcpprelu_neg`, x)
}

#' Function used as part of other functions
#'
#'
#' @description Used as part of other functions.
#' @param x A matrix of predictors for the training dataset
#' @param y A vector of output values for the training data with a length similar to the number of rows of x
#' @param testx A matrix of predictors for the test dataset
#' @param testy A vector of output values for the test data with a length similar to the number of rows of x
#' @param W1_input Input-hidden layer weights
#' @param B1_input Biases for the hidden layer
#' @param W2_input Hidden-output layer weights
#' @param B2_input Bias for the output layer (the baseline risk)
#' @param lr Initial learning rate
#' @param maxepochs The maximum number of epochs
#' @param baseline_risk_reward increasing parameter value at each iteration
#' @param IPCW Inverse probability of censoring weights (Warning: not yet correctly implemented)
#' @return A list of class "SCL" giving the estimated matrices and performance indicators
#' @author    Andreas Rieckmann, Piotr Dworzynski, Claus Ekstrøm
#'
#' @export
SRCL_cpp_train_network_relu <- function(x, y, testx, testy, W1_input, B1_input, W2_input, B2_input, IPCW, lr = 0.01, maxepochs = 100, L1 = 0.00001) {
    .Call(`_SRCL_SRCL_cpp_train_network_relu`, x, y, testx, testy, W1_input, B1_input, W2_input, B2_input, IPCW, lr, maxepochs, L1)
}

#' Function used as part of other functions
#'
#'
#' @description Used as part of other functions.
#' @param x A matrix of predictors for the training dataset
#' @param y A vector of output values for the training data with a length similar to the number of rows of x
#' @param c A matrix of predictors for the training data to be regarded as potential confounder(s)
#' @param testx A matrix of predictors for the test dataset
#' @param testy A vector of output values for the test data with a length similar to the number of rows of x
#' @param testc A matrix of predictors for the test data to be regarded as potential confounder(s)
#' @param W1_input Input-hidden layer weights
#' @param B1_input Biases for the hidden layer
#' @param W2_input Hidden-output layer weights
#' @param B2_input Bias for the output layer (the baseline risk)
#' @param C2_input Weight for the confounder
#' @param lr Initial learning rate
#' @param maxepochs The maximum number of epochs
#' @return A list of class "SCL" giving the estimated matrices and performance indicators
#' @author    Andreas Rieckmann, Piotr Dworzynski, Claus Ekstrøm
#'
#' @export
SRCL_cpp_train_network_relu_with_confounder <- function(x, y, c, testx, testy, testc, W1_input, B1_input, W2_input, B2_input, C2_input, lr = 0.01, maxepochs = 100) {
    .Call(`_SRCL_SRCL_cpp_train_network_relu_with_confounder`, x, y, c, testx, testy, testc, W1_input, B1_input, W2_input, B2_input, C2_input, lr, maxepochs)
}

